# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'algorithm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for algorithm

pod 'ReactiveCocoa', '2.5'

  target 'algorithmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'algorithmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
